=== IPSpb/XSLT/task1/chapter.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="chapter">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="title" type="xs:string" />
            <xs:element name="section" maxOccurs="unbounded" type="section" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:complexType name="section">
    <xs:sequence>
        <xs:element name="title" type="xs:string" />
        <xs:element name="para" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:integer" />
</xs:complexType>
</xs:schema>

=== IPSpb/XSLT/task1/announcements.xml
<?xml version="1.0" encoding="UTF-8"?>
<chapter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chapter.xsd">
    <title>Объявления</title>
    <section id="1">
        <title>Понижение комиссии</title>
        <para>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda at commodi corporis dolorem ducimus eveniet ex expedita fugit incidunt ipsa maiores, minus obcaecati porro praesentium quas rem sit, tenetur ut.</para>
    </section>
    <section id="2">
        <title>Приостановка работы</title>
        <para>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda at commodi corporis dolorem ducimus eveniet ex expedita fugit incidunt ipsa maiores, minus obcaecati porro praesentium quas rem sit, tenetur ut.</para>
    </section>
    <section id="3">
        <title>Новые условия</title>
        <para>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda at commodi corporis dolorem ducimus eveniet ex expedita fugit incidunt ipsa maiores, minus obcaecati porro praesentium quas rem sit, tenetur ut.</para>
    </section>
</chapter>
